name: PixelBuy
main: com.saicone.pixelbuy.PixelBuy

authors: [Rubenicos]

api-version: 1.13
version: ${version}

description: Free plugin for donation system

softdepend: [PlaceholderAPI, Oraxen, MMOItems]