# Plugin configuration
Plugin:
  # 1 = errors, 2 = warnings, 3 = information, 4 = debug
  # Set to 0 to disable
  LogLevel: 3
  # Available languages: en_US, es_ES
  # If you want to use other language go to "lang" folder and create new file
  Language: 'en_US'

# Lang configuration
Lang:
  # Default player language
  Default: 'en_US'
  # Language aliases
  Aliases:
    en_US:
      - 'en_AU'
      - 'en_CA'
      - 'en_GB'
      - 'en_NZ'
    es_ES:
      - 'es_AR'
      - 'es_CL'
      - 'es_EC'
      - 'es_MX'
      - 'es_UY'
      - 'es_VE'

# Database configuration
Database:
  # If false the data will be saved using player names (Recommended for No-Premium servers)
  UUID: false
  # Available types: JSON, MYSQL
  # JSON: Data will be saved on json files in "playerdata" folder
  # MYSQL: Data will be saved on external database
  Type: JSON
  # Configuration about MySQL database
  # Don't edit this if you are using JSON database type
  Host: 'localhost:3306'
  Database: 'database'
  User: 'user'
  Password: 'pass'
  Flags: '?autoReconnect=true&verifyServerCertificate=false&useSSL=false'
  # Set to true to convert JSON files data automatically to external database data if you change
  # database type or the external database has an error who changes the database type to json
  Convert-Data: true

# Configuration about WooCommerce connection
Web-Data:
  # Interval in seconds to check if exists new orders
  # This checker don't require so much CPU, 7 seconds is recommended
  # Set to -1 to disable
  Check-Interval: 7
  # URL of your site WITHOUT "/" at final
  # For example http://shop.mysite.com
  URL: ''
  # This is a key that YOU set, both needing to be identical
  # in the WooCommerce configuration and in this config file
  Key: ''

# Configuration about orders
Order:
  # Delay on seconds order sending to player
  Delay: 5

# Configuration about plugin command
# Yes, you can edit command name and aliases
Commands:
  # Main command configuration
  Main:
    Cmd: 'pixelbuy'
    Aliases:
      - 'pbuy'

# Permissions configuration
Perms:
  # All permissions
  All: 'pixelbuy.*'
  # Commands permissions
  Main: 'pixelbuy.use'
  Database: 'pixelbuy.database'
  PlayerData: 'pixelbuy.playerdata'
  Reload: 'pixelbuy.reload'
  Store: 'pixelbuy.store'
