# Plugin configuration
Plugin:
  # 1 = errors, 2 = warnings, 3 = information, 4 = debug
  # Set to 0 to disable
  LogLevel: 3
  # Available languages: en_US, es_ES
  # If you want to use other language go to "lang" folder and create new file
  Language: 'en_US'
  # Player UUID provider:
  # AUTO     = Choose automatically the best available option
  # PIXELBUY = Use PixelBuy loaded data (the option LoadUsers on store.yml must be activated)
  # BUKKIT   = Use the deprecated Bukkit UUID solution (it also acts like fallback value)
  UUIDProvider: AUTO

# Lang configuration
Lang:
  # Default player language
  Default: 'en_US'
  # Language aliases
  Aliases:
    en_US:
      - 'en_AU'
      - 'en_CA'
      - 'en_GB'
      - 'en_NZ'
    es_ES:
      - 'es_AR'
      - 'es_CL'
      - 'es_EC'
      - 'es_MX'
      - 'es_UY'
      - 'es_VE'

# Database configuration
Database:
  # Database types:
  # - SQL
  Type: SQL
  # Sql database configuration
  Sql:
    # Local sql databases (no additional config needed):
    # - H2 (recommended)
    # - SQLITE
    #
    # External sql databases:
    # - MYSQL
    # - MARIADB
    # - POSTGRESQL
    Type: H2
    # Table prefix
    TablePrefix: 'pixelbuy_'
    # Database host
    Host: localhost
    # Database port
    Port: 3306
    # Database name
    Database: database
    # Username credential for connection
    Username: root
    # Password credential for connection
    Password: password
    # Database flags
    Flags:
      - 'useSSL=false'
      - 'verifyServerCertificate=false'

# Plugin commands configuration
Commands:
  # Main command configuration
  PixelBuy:
    # Make command accessible as root command
    register: true
    # Command name
    name: 'pixelbuy'
    # Command aliases
    aliases:
      - 'pbuy'
    # Command permission
    permission: 'pixelbuy.command'
  Reload:
    name: 'reload'
    permission: 'pixelbuy.command.reload'
  User:
    name: 'user'
    aliases:
      - 'player'
    permission: 'pixelbuy.command.player'
  Order:
    name: 'order'
    permission: 'pixelbuy.command.order'
  Data:
    name: 'data'
    aliases:
      - 'database'
    permission: 'pixelbuy.command.data'
  Store:
    register: true
    name: 'store'
    aliases:
      - 'buy'
    permission: 'pixelbuy.command.store'
