# Plugin configuration
Plugin:
  # 1 = errors, 2 = warnings, 3 = information, 4 = debug
  # Set to 0 to disable
  LogLevel: 3
  # Available languages: en_US, es_ES
  # If you want to use other language go to "lang" folder and create new file
  Language: 'en_US'

# Lang configuration
Lang:
  # Default player language
  Default: 'en_US'
  # Language aliases
  Aliases:
    en_US:
      - 'en_AU'
      - 'en_CA'
      - 'en_GB'
      - 'en_NZ'
    es_ES:
      - 'es_AR'
      - 'es_CL'
      - 'es_EC'
      - 'es_MX'
      - 'es_UY'
      - 'es_VE'

# Database configuration
Database:
  # Database types:
  # - SQL
  Type: SQL
  # Load or not all players data to generate top donors
  LoadAll: true
  # Sql database configuration
  Sql:
    # Local sql databases (no additional config needed):
    # - H2 (recommended)
    # - SQLITE
    #
    # External sql databases:
    # - MYSQL
    # - MARIADB
    # - POSTGRESQL
    Type: H2
    # Table prefix
    TablePrefix: 'pixelbuy_'
    # Database host
    Host: localhost
    # Database port
    Port: 3306
    # Database name
    Database: database
    # Username credential for connection
    Username: root
    # Password credential for connection
    Password: password
    # Database flags
    Flags:
      - 'useSSL=false'
      - 'verifyServerCertificate=false'

# Configuration about orders
Order:
  # Delay on seconds order sending to player
  Delay: 5

# Configuration about plugin command
# Yes, you can edit command name and aliases
Commands:
  # Main command configuration
  Main:
    Cmd: 'pixelbuy'
    Aliases:
      - 'pbuy'

# Permissions configuration
Perms:
  # All permissions
  All: 'pixelbuy.*'
  # Commands permissions
  Main: 'pixelbuy.use'
  Database: 'pixelbuy.database'
  PlayerData: 'pixelbuy.playerdata'
  Reload: 'pixelbuy.reload'
  Store: 'pixelbuy.store'
