# Plugin configuration
Plugin:
  # 1 = errors, 2 = warnings, 3 = information, 4 = debug
  # Set to 0 to disable
  LogLevel: 3
  # Available languages: en_US, es_ES
  # If you want to use other language go to "lang" folder and create new file
  Language: 'en_US'
  # Player UUID provider:
  # AUTO     = Choose automatically the best available option
  # PIXELBUY = Use PixelBuy loaded data (the option loadAll user on database configuration must be activated)
  # BUKKIT   = Use the deprecated Bukkit UUID solution (it also acts like fallback value)
  UUIDProvider: AUTO

# Lang configuration
Lang:
  # Default player language
  Default: 'en_US'
  # Language aliases
  Aliases:
    en_US:
      - 'en_AU'
      - 'en_CA'
      - 'en_GB'
      - 'en_NZ'
    es_ES:
      - 'es_AR'
      - 'es_CL'
      - 'es_EC'
      - 'es_MX'
      - 'es_UY'
      - 'es_VE'

# Database configuration
Database:
  # User data configuration
  User:
    # Load or not all user data (name, uuid, donations) into memory
    # This option also make available the top donors option
    LoadAll: true
  # Top donors configuration
  Top:
    # Top limit
    # Set to -1 to calculate a top position for every user
    Limit: -1
    # Time in ticks between top calculation
    # 20 ticks = 1 second
    # Set to -1 to disable
    Time: 6000
  # Database types:
  # - SQL
  Type: SQL
  # Sql database configuration
  Sql:
    # Local sql databases (no additional config needed):
    # - H2 (recommended)
    # - SQLITE
    #
    # External sql databases:
    # - MYSQL
    # - MARIADB
    # - POSTGRESQL
    Type: H2
    # Table prefix
    TablePrefix: 'pixelbuy_'
    # Database host
    Host: localhost
    # Database port
    Port: 3306
    # Database name
    Database: database
    # Username credential for connection
    Username: root
    # Password credential for connection
    Password: password
    # Database flags
    Flags:
      - 'useSSL=false'
      - 'verifyServerCertificate=false'

# Messenger configuration
Messenger:
  # Enable or not this feature
  Enabled: false
  # Channel name
  Channel: 'pixelbuy:main'
  # Messenger types:
  # AUTO     = Choose automatically the best available option
  # SQL      = Use the current SQL database if it's an external database type
  # REDIS    = Use a Redis server for messaging (configure it below)
  # RABBITMQ = Use a RabbitMQ server for messaging (configure it below)
  Type: AUTO
  # Redis configuration
  Redis:
    # Redis url connection
    #
    # URL format: redis://[user]:[password@]host[:port][/databaseNumber]
    Url: 'redis://:password@localhost:6379/0'
  # RabbitMQ configuration
  RabbitMQ:
    # This is like the "pre-channel", the way to access the messaging channels
    # You can use the same exchange in multiple servers with different channels
    Exchange: 'pixelbuy'
    # RabbitMQ url connection
    # Documentation: https://www.rabbitmq.com/uri-spec.html
    #
    # URL: amqp://userName:password@hostName:portNumber/virtualHost
    # If the virtual host is "/", set has "%2F"
    Url: 'amqp://guest:guest@localhost:5672/%2F'

# PlaceholderAPI hook configuration
Placeholder:
  # Register or not the placeholder expansion
  Register: true
  # The names to use for placeholder
  Names:
    - 'pixelbuy'
    - 'pbuy'

# Plugin commands configuration
Commands:
  # Main command configuration
  PixelBuy:
    # Make command accessible as root command
    register: true
    # Command name
    name: 'pixelbuy'
    # Command aliases
    aliases:
      - 'pbuy'
    # Command permission
    permission: 'pixelbuy.command'
    # Delay in seconds between execute this command
    # This only take effect if the command is registered
    # Set to -1 to disable
    delay: -1
  Reload:
    name: 'reload'
    permission: 'pixelbuy.command.reload'
  User:
    name: 'user'
    aliases:
      - 'player'
    permission: 'pixelbuy.command.player'
  Order:
    name: 'order'
    permission: 'pixelbuy.command.order'
  Data:
    name: 'data'
    aliases:
      - 'database'
    permission: 'pixelbuy.command.data'
  Store:
    register: true
    name: 'store'
    aliases:
      - 'buy'
    permission: 'pixelbuy.command.store'
