# Item unique id
super-pickaxe:
  # Item price
  price: 2.49
  # Item categories
  categories:
    - 'items'
  # Item display configuration on shop gui
  display:
    material: DIAMOND_PICKAXE
    name: '&9&lSuper Pickaxe'
    lore:
      - ''
      - '&7Price&8: &a{item_price}'
      - ''
      - '&7Get on the server store'
  # Shop item options
  options:
    # Set to true if this store item only can be given if the player is online
    # This option affects other items in the same order
    online: true
    # True to give this item without being affected by online store items
    always-run: false
    # Group names to append this store item
    append:
      - 'global'
  # Executable events on buy
  onBuy:
    - item:
        material: DIAMOND_PICKAXE
        amount: 1
        name: '&9&lSuper Pickaxe'
        lore:
          - '&7Custom pickaxe'
          - '&7from server store'
          - ''
          - '&6Buyer: &7%player_name%'
          - '&6Order ID: &7{order_id}'
        enchants:
          SHARPNESS: 10
          DIG_SPEED: 5
          LOOT_BONUS_BLOCKS: 20
    - message: '&e&lYou bought the &9&lSuper Pickaxe&e!'
    - broadcast:
        - '&e-----------------------------'
        - '&fThe player &e{user_name} &fbought the super pickaxe!'
        - '&e-----------------------------'

rank-vip:
  price: 3
  category: 'ranks'
  display:
    material: DIAMOND
    name: '&e&lVIP Rank'
  onBuy:
    - command: 'lp user {user_name} parent add vip'
    - broadcast:
        - '&e-----------------------------'
        - '&fThe player &e{user_name} &fbought the VIP rank!'
        - '&e-----------------------------'
  # Executable events on refund
  onRefund:
    - command: 'lp user {user_name} parent remove vip'

eco-bundle:
  price: 1.99
  display:
    material: EMERALD
    name: '&a&lEco Bundle'
  onBuy:
    - command: 'eco give {user_name} 1000'
    - broadcast:
        - '&e-----------------------------'
        - '&fThe player &e{user_name} &fbought the eco bundle!'
        - '&e-----------------------------'
  onRefund:
    - command: 'eco take {user_name} 1000'
